name: vtweb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  path_provider: ^2.0.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  firebase_core: ^2.25.4
  cloud_functions: ^4.6.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background (1).png
    - assets/images/background (2).png
    - assets/images/background (3).png
    - assets/images/background (4).png
    - assets/images/background (5).png
    - assets/images/background (6).png
    - assets/images/background (7).png
    - assets/images/background (8).png
    - assets/images/background (9).png
    - assets/images/background (10).png
    - assets/images/background (11).png



